# Generated by Django 5.2.7 on 2025-11-09 10:49

import django.db.models.deletion
import user_data_api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_id', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('notifications', models.JSONField(blank=True, default=list, help_text='Lista de alertas de notificação aninhados.')),
                ('preferences', models.JSONField(default=user_data_api.models.UserData.get_default_preferences, help_text='Preferências do usuário, como idioma e fuso horário.')),
            ],
            options={
                'verbose_name': 'Dados do Usuário (MongoDB)',
                'verbose_name_plural': 'Dados dos Usuários (MongoDB)',
            },
        ),
    ]
