# Generated by Django 5.2.7 on 2025-11-11 09:27

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Feature', max_length=20)),
                ('properties', models.JSONField()),
                ('geometry', models.JSONField()),
            ],
        ),
    ]
